/*
Applicant model
 */
module.exports = function(sequelize, DataTypes) {
  var Applicant = sequelize.define('Applicant', {
    firstName: {
      type: DataTypes.STRING,
      allowNull: false
    },
    lastName: {
      type: DataTypes.STRING,
      allowNull: false
    },
    numYes: {
      type: DataTypes.INTEGER,
      allowNull: true
    },
    numNo: {
      type: DataTypes.INTEGER,
      allowNull: true
    },
    isAnchored: {
      type: DataTypes.BOOLEAN,
      defaultValue: false
    }
  }, {
    timestamps: true,
    paranoid: true
  });
  return Applicant;
};

// ---
// generated by coffee-script 1.9.2