/*
Medic model
 */
module.exports = function(sequelize, DataTypes) {
  var Medic;
  Medic = sequelize.define('Medic', {
    firstName: {
      type: DataTypes.STRING,
      allowNull: false
    },
    lastName: {
      type: DataTypes.STRING,
      allowNull: false
    },
    phone: {
      type: DataTypes.STRING,
      allowNull: false,
      validate: {
        len: {
          args: [10, 10],
          msg: 'You need to include a valid phone number of length 10!'
        },
        isNumeric: {
          args: true,
          msg: 'Phone number must be only numbers!'
        }
      }
    },
    baseRank: {
      type: DataTypes.STRING,
      allowNull: false,
      validate: {
        isIn: ['E', 'C']
      }
    },
    curRank: {
      type: DataTypes.STRING,
      validate: {
        isIn: ['EC', 'ES', 'CS']
      }
    }
  }, {
    timestamps: true,
    paranoid: true
  });
  return Medic;
};

// ---
// generated by coffee-script 1.9.2